cscript util\ChangeEOL.vbs Data\default.txt Disk\default
cscript util\ChangeEOL.vbs Data\init.txt Disk\init
cscript util\ChangeEOL.vbs Data\monster.txt Disk\monster
cscript util\ChangeEOL.vbs Data\node1.txt Disk\node1
cscript util\ChangeEOL.vbs Data\node2.txt Disk\node2
cscript util\ChangeEOL.vbs Data\node3.txt Disk\node3
cscript util\ChangeEOL.vbs Data\node4.txt Disk\node4
cscript util\ChangeEOL.vbs Data\node5.txt Disk\node5
cscript util\ChangeEOL.vbs Data\node6.txt Disk\node6
cscript util\ChangeEOL.vbs Data\node7.txt Disk\node7
cscript util\ChangeEOL.vbs Data\node8.txt Disk\node8
cscript util\ChangeEOL.vbs Data\node9.txt Disk\node9
cscript util\ChangeEOL.vbs Data\node10.txt Disk\node10
cscript util\ChangeEOL.vbs Data\node11.txt Disk\node11
cscript util\ChangeEOL.vbs Data\node12.txt Disk\node12
cscript util\ChangeEOL.vbs Data\node13.txt Disk\node13
cscript util\ChangeEOL.vbs Data\node14.txt Disk\node14
cscript util\ChangeEOL.vbs Data\node15.txt Disk\node15
cscript util\ChangeEOL.vbs Data\node16.txt Disk\node16
cscript util\ChangeEOL.vbs Data\node17.txt Disk\node17
cscript util\ChangeEOL.vbs Data\node18.txt Disk\node18
cscript util\ChangeEOL.vbs Data\node19.txt Disk\node19
cscript util\ChangeEOL.vbs Data\node20.txt Disk\node20
cscript util\ChangeEOL.vbs Data\node21.txt Disk\node21
cscript util\ChangeEOL.vbs Data\node22.txt Disk\node22
cscript util\ChangeEOL.vbs Data\node23.txt Disk\node23
cscript util\ChangeEOL.vbs Data\node24.txt Disk\node24
cscript util\ChangeEOL.vbs Data\node25.txt Disk\node25
cscript util\ChangeEOL.vbs Data\node26.txt Disk\node26
cscript util\ChangeEOL.vbs Data\node27.txt Disk\node27
cscript util\ChangeEOL.vbs Data\node28.txt Disk\node28
cscript util\ChangeEOL.vbs Data\node29.txt Disk\node29
cscript util\ChangeEOL.vbs Data\node30.txt Disk\node30
cscript util\ChangeEOL.vbs Data\node31.txt Disk\node31
cscript util\ChangeEOL.vbs Data\node32.txt Disk\node32
cscript util\ChangeEOL.vbs Data\node33.txt Disk\node33
cscript util\ChangeEOL.vbs Data\node34.txt Disk\node34
cscript util\ChangeEOL.vbs Data\node35.txt Disk\node35
cscript util\ChangeEOL.vbs Data\node36.txt Disk\node36
cscript util\ChangeEOL.vbs Data\node37.txt Disk\node37
cscript util\ChangeEOL.vbs Data\node38.txt Disk\node38
cscript util\ChangeEOL.vbs Data\node39.txt Disk\node39
cscript util\ChangeEOL.vbs Data\node40.txt Disk\node40
cscript util\ChangeEOL.vbs Data\node41.txt Disk\node41
cscript util\ChangeEOL.vbs Data\node42.txt Disk\node42
cscript util\ChangeEOL.vbs Data\node43.txt Disk\node43
cscript util\ChangeEOL.vbs Data\node44.txt Disk\node44
cscript util\ChangeEOL.vbs Data\node45.txt Disk\node45
cscript util\ChangeEOL.vbs Data\node46.txt Disk\node46
cscript util\ChangeEOL.vbs Data\node47.txt Disk\node47
cscript util\ChangeEOL.vbs Data\node48.txt Disk\node48
cscript util\ChangeEOL.vbs Data\node49.txt Disk\node49
cscript util\ChangeEOL.vbs Data\node50.txt Disk\node50
cscript util\ChangeEOL.vbs Data\node51.txt Disk\node51
cscript util\ChangeEOL.vbs Data\node52.txt Disk\node52
cscript util\ChangeEOL.vbs Data\node53.txt Disk\node53
cscript util\ChangeEOL.vbs Data\node54.txt Disk\node54

util\dir2atr -b Dos25 Data.atr Disk